config/routes.rb
StickerThings::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'stickers#index'
  resources :stickers
  get '/faq' => 'stickers#faq'
  get '/categories' => 'stickers#categories'
  get '/:tag' => 'stickers#index', :as => :stickers_tag_index

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/sticker.rb
class Sticker < ActiveRecord::Base
  has_attached_file :sticker
  validates_attachment_content_type :sticker, :content_type => "image/png"

  has_attached_file :sticker_preview, :styles => { :medium => "250x250"}
  validates_attachment_content_type :sticker_preview, :content_type => "image/png"

  acts_as_taggable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/stickers_controller.rb
class StickersController < ApplicationController

  def index
  	if params[:tag].blank?
    @stickers=Sticker.paginate(:page => params[:page], :per_page => 50)
    else
    @stickers=Sticker.tagged_with(params[:tag]).paginate(:page => params[:page], :per_page => 50)
    end
  end

  def show
  	@sticker=Sticker.find_by_id(params[:id])
  end

  def categories
  	@tags = Sticker.tag_counts_on(:tags)
  	render 'categories'
  end

  def faq
  	render 'faq'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stickers_helper.rb
module StickersHelper
	include ActsAsTaggableOn::TagsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>stickerthings</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <link href='http://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Nixie+One' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body id="body">
<%= render "/menu_bar" %>

<%= yield %>

</body>
</html>

app/views/stickers/categories.html.erb
<div id="main_content_wrapper">
	<div id="the_tag_cloud">
		<% tag_cloud(@tags, %w(css1 css2 css3 css4)) do |tag, css_class| %>
		  <%= link_to tag.name, stickers_tag_index_path(:tag => tag.name), :class => css_class %>
		<% end %>
	</div>
</div>

app/views/stickers/faq.html.erb
<div id="main_content_wrapper">
 <div class="page" >
  <h2>What is Stickerthings?</h2>
  <p>It's a growing collection of cut-out people, plants, pets and other things ready to stick into your designs! All the stickers are high resolution PNG files, with transparent backgrounds to save on valuable photoshop time. Best of all, they're completely free to use as much as you want.</p>
  <h2>Who are they for?</h2>
  <p>Architects! Landscape Architects! Interior Designers! Industrial Designers! Anyone! As an (almost ex) architecture student, I know how time consuming it can be to have to carefully crop out backgrounds to create your own cut-outs. So save yourself some photoshop time and use mine instead! Your renders will thank you. </p>
  <h2>How do I use them?</h2>
  <p>You can browse all the stickers from the <%=link_to('home', root_path) %> page, or search for specific things via the tags on the <%=link_to('categories', categories_path) %> page. Once you find a sticker you like, click on it to link through to the high resolution version, then just right click and 'Save Image As'.</p>
  <h2>Is it free?</h2>
  <p>Yep, all the stickers are free to use for creative work (educational or commercial), with no sign-up required.</p>
 </div>
</div>

app/views/stickers/index.html.erb
<div id="main_content_wrapper">
 <div class="page" >
  <% @stickers.each do |sticker| %>
  <%=link_to(image_tag(sticker.sticker_preview.url(:medium), class: "sticker_preview_image"), sticker_path(id: sticker.id))%>
  <% end %>
 </div>
  <%= will_paginate(@stickers, :next_label => '>', :previous_label => '<') %>
</div>

app/views/stickers/show.html.erb
<div id="main_content_wrapper">
  <%= image_tag(@sticker.sticker.url, class: "show_sticker_image") %>
  <br/>
  <br/>
  <br/>
  <br/>
  <span id="instructions">
  Right click and 'Save Image As' to save the full resolution sticker above to your computer.
  </span>
    <br/>
  <br/>
  <br/>
  <div class="back_button">
   <%= link_to("back", :back) %>
  </div>
</div>